/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.source.Form;

import com.source.Main.Main;
import com.source.Sql.connectDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class doimatkhau extends javax.swing.JPanel {

    /**
     * Creates new form doimatkhau
     */
    public doimatkhau() {
        initComponents();
        inTableQLTK();
        inTableQLTKNH();
    }
    connectDB cn = new connectDB();
    Connection conn;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        loginAdmin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        dangnhap = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        settingAdmin = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        taotk = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        suatk = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        xoatk = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        themtknh = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        suatknh = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        xoatknh = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        themtknh1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel6.setLayout(new java.awt.CardLayout());

        loginAdmin.setBackground(new java.awt.Color(153, 153, 153));
        loginAdmin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                loginAdminMouseMoved(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Tên đăng nhập:");

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Mật khẩu:");

        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel3.setText("Truy cập với quyền người quản lý");

        dangnhap.setBackground(new java.awt.Color(102, 102, 102));
        dangnhap.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                dangnhapMouseMoved(evt);
            }
        });
        dangnhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dangnhapMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Đăng nhập");

        javax.swing.GroupLayout dangnhapLayout = new javax.swing.GroupLayout(dangnhap);
        dangnhap.setLayout(dangnhapLayout);
        dangnhapLayout.setHorizontalGroup(
            dangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dangnhapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dangnhapLayout.setVerticalGroup(
            dangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dangnhapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginAdminLayout = new javax.swing.GroupLayout(loginAdmin);
        loginAdmin.setLayout(loginAdminLayout);
        loginAdminLayout.setHorizontalGroup(
            loginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginAdminLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(loginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(loginAdminLayout.createSequentialGroup()
                        .addGroup(loginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(134, 134, 134))
        );
        loginAdminLayout.setVerticalGroup(
            loginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginAdminLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addGroup(loginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(dangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jPanel6.add(loginAdmin, "card3");

        settingAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên", "Tên tài khoản", "Mật khẩu", "Quyền hạn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Tên");

        jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("ID");

        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Tài khoản");

        jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Mật khẩu");

        jTextField13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Quyền hạn");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quanly", "Nhanvien" }));

        taotk.setBackground(new java.awt.Color(102, 102, 102));
        taotk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taotkMouseClicked(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Tạo");

        javax.swing.GroupLayout taotkLayout = new javax.swing.GroupLayout(taotk);
        taotk.setLayout(taotkLayout);
        taotkLayout.setHorizontalGroup(
            taotkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taotkLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel23)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        taotkLayout.setVerticalGroup(
            taotkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taotkLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addContainerGap())
        );

        suatk.setBackground(new java.awt.Color(102, 102, 102));
        suatk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suatkMouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Sửa");

        javax.swing.GroupLayout suatkLayout = new javax.swing.GroupLayout(suatk);
        suatk.setLayout(suatkLayout);
        suatkLayout.setHorizontalGroup(
            suatkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suatkLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel24)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        suatkLayout.setVerticalGroup(
            suatkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suatkLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addContainerGap())
        );

        xoatk.setBackground(new java.awt.Color(102, 102, 102));
        xoatk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xoatkMouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Xóa");

        javax.swing.GroupLayout xoatkLayout = new javax.swing.GroupLayout(xoatk);
        xoatk.setLayout(xoatkLayout);
        xoatkLayout.setHorizontalGroup(
            xoatkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xoatkLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel25)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        xoatkLayout.setVerticalGroup(
            xoatkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xoatkLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(suatk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(xoatk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(taotk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taotk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suatk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xoatk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
        );

        settingAdmin.addTab("Quản lý tài khoản", jPanel8);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã ngân hàng", "Tên ngân hàng", "Tên tài khoản", "Số tài khoản", "Mã Bin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setRowHeight(25);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("STT");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Số tài khoản");

        jTextField15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Tên tài khoản");

        jTextField17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        themtknh.setBackground(new java.awt.Color(102, 102, 102));
        themtknh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                themtknhMouseClicked(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Thêm");

        javax.swing.GroupLayout themtknhLayout = new javax.swing.GroupLayout(themtknh);
        themtknh.setLayout(themtknhLayout);
        themtknhLayout.setHorizontalGroup(
            themtknhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(themtknhLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel29)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        themtknhLayout.setVerticalGroup(
            themtknhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(themtknhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        suatknh.setBackground(new java.awt.Color(102, 102, 102));
        suatknh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suatknhMouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Sửa");

        javax.swing.GroupLayout suatknhLayout = new javax.swing.GroupLayout(suatknh);
        suatknh.setLayout(suatknhLayout);
        suatknhLayout.setHorizontalGroup(
            suatknhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suatknhLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel30)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        suatknhLayout.setVerticalGroup(
            suatknhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suatknhLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addContainerGap())
        );

        xoatknh.setBackground(new java.awt.Color(102, 102, 102));
        xoatknh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xoatknhMouseClicked(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Xóa");

        javax.swing.GroupLayout xoatknhLayout = new javax.swing.GroupLayout(xoatknh);
        xoatknh.setLayout(xoatknhLayout);
        xoatknhLayout.setHorizontalGroup(
            xoatknhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xoatknhLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel31)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        xoatknhLayout.setVerticalGroup(
            xoatknhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xoatknhLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addContainerGap())
        );

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel32.setText("Ngân hàng");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agribank", "VietinBank", "SCB", "DongA Bank", "Techcombank", "MB Bank", "Vietcombank", "ACB", "VPBank", "BIDV", " " }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(themtknh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(suatknh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(xoatknh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel32))
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField15, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, 1, Short.MAX_VALUE))
                .addGap(75, 75, 75)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xoatknh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(themtknh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suatknh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
        );

        settingAdmin.addTab("Thông tin chuyển khoản", jPanel5);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));

        themtknh1.setBackground(new java.awt.Color(102, 102, 102));
        themtknh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                themtknh1MouseClicked(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Thoát");

        javax.swing.GroupLayout themtknh1Layout = new javax.swing.GroupLayout(themtknh1);
        themtknh1.setLayout(themtknh1Layout);
        themtknh1Layout.setHorizontalGroup(
            themtknh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(themtknh1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel33)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        themtknh1Layout.setVerticalGroup(
            themtknh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(themtknh1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(532, Short.MAX_VALUE)
                .addComponent(themtknh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(284, Short.MAX_VALUE)
                .addComponent(themtknh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        settingAdmin.addTab("Thoát", jPanel7);

        jPanel6.add(settingAdmin, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dangnhapMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dangnhapMouseMoved
        // TODO add your handling code here:
        dangnhap.setBackground(new java.awt.Color(87, 82, 82));
    }//GEN-LAST:event_dangnhapMouseMoved

    private void loginAdminMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginAdminMouseMoved
        // TODO add your handling code here:
        dangnhap.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_loginAdminMouseMoved

    private void dangnhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dangnhapMouseClicked
        // TODO add your handling code here:
        try {
            conn = new connectDB().getConnection();
        } catch (Exception e) {
            e.printStackTrace();
        }
        //chọn từ bảng QLTK chổ taikhoan và matkhau với quyen quanly
        String sql = "select * from NhanVien where taikhoan = ? and matkhau = ? and quyenhan = 'Quanly'";
        try{
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, jTextField1.getText());
            ps.setString(2, jPasswordField1.getText());
            ResultSet rs = ps.executeQuery();
            if(jTextField1.getText().equals("") || jPasswordField1.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
            }
            else if(rs.next()){
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
                loginAdmin.setVisible(false);
                settingAdmin.setVisible(true);
                jTextField1.setText("");
                jPasswordField1.setText("");
            }
            
            else {
                JOptionPane.showMessageDialog(this, "Đăng nhập thất bại");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_dangnhapMouseClicked

    private void taotkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taotkMouseClicked
        // TODO add your handling code here:
        try {
            conn = new connectDB().getConnection();
            String sql = "SELECT * FROM NhanVien WHERE maNV = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, jTextField11.getText());
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Mã ID đã tồn tại");
            } else if(jTextField10.getText().equals("")||jTextField12.getText().equals("")||jTextField13.getText().equals("")||jTextField11.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
            }
             else {
                try {
                    String sql1 = "INSERT INTO NhanVien (maNV, ten, taikhoan, matkhau, quyenhan, trangthai) VALUES (?, ?, ?, ?, ?, ?)";
                    PreparedStatement ps1 = conn.prepareStatement(sql1);
                    ps1.setString(1, jTextField11.getText());
                    ps1.setString(2, jTextField10.getText());
                    ps1.setString(3, jTextField13.getText());
                    ps1.setString(4, jTextField12.getText());
                    ps1.setString(5, jComboBox1.getSelectedItem().toString());
                    ps1.setString(6, "0");
                    ps1.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Tạo tài khoản thành công");
                    inTableQLTK();
                    jTextField10.setText("");
                    jTextField11.setText("");
                    jTextField12.setText("");
                    jTextField13.setText("");
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_taotkMouseClicked

    private void suatkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suatkMouseClicked
        // TODO add your handling code here:
        try {
            conn = new connectDB().getConnection();
        } catch (Exception e) {
            e.printStackTrace();
        }
        if(jTextField10.getText().equals("")||jTextField11.getText().equals("")||jTextField12.getText().equals("")||jTextField13.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
            return;
        }
        else{
            try{
                String sql = "update NhanVien set ten = ?, taikhoan = ?, matkhau = ?, quyenhan = ? where maNV = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, jTextField10.getText());
                ps.setString(2, jTextField13.getText());
                ps.setString(3, jTextField12.getText());
                ps.setString(4, jComboBox1.getSelectedItem().toString());
                ps.setString(5, jTextField11.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Sửa thành công");
                inTableQLTK();

            } catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_suatkMouseClicked

    private void xoatkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoatkMouseClicked
        // TODO add your handling code here:
        try {
            conn = new connectDB().getConnection();
        } catch (Exception e) {
            e.printStackTrace();
        }
        if(jTextField11.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn tài khoản cần xóa");
            return;
        }
        else{
            try{
                String sql = "delete from NhanVien where maNV = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, jTextField11.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                inTableQLTK();

            } catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_xoatkMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int index = jTable1.getSelectedRow();
        if(index>=0){
            jTextField11.setText(model.getValueAt(index, 0).toString());
            jTextField10.setText(model.getValueAt(index, 1).toString());
            jTextField13.setText(model.getValueAt(index, 2).toString());
            jTextField12.setText(model.getValueAt(index, 3).toString());
            jComboBox1.setSelectedItem(model.getValueAt(index, 4).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int index = jTable2.getSelectedRow();
        if(index>=0){
            jTextField15.setText(model.getValueAt(index, 0).toString());
            jComboBox2.setSelectedItem(model.getValueAt(index, 1).toString());
            jTextField16.setText(model.getValueAt(index, 2).toString());
            jTextField17.setText(model.getValueAt(index, 3).toString());
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void themtknhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_themtknhMouseClicked
        // TODO add your handling code here:
        try {

            Map<String, String> bankCodes = new HashMap<>();
            bankCodes.put("MB Bank", "970422");
            bankCodes.put("Agribank", "3");
            bankCodes.put("VietinBank", "2");
            bankCodes.put("SCB", "970401");
            bankCodes.put("DongA Bank", "970402");
            bankCodes.put("Techcombank", "970403");
            bankCodes.put("Vietcombank", "970404");
            bankCodes.put("ACB", "970406");
            bankCodes.put("VPBank", "970407");
            bankCodes.put("BIDV", "970408");


            conn = new connectDB().getConnection();
            String sql = "SELECT * FROM TaiKhoanNganHang WHERE maNH = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, jTextField15.getText());
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Mã NH đã tồn tại");
            } else if(jTextField15.getText().equals("")||jTextField16.getText().equals("")||jTextField17.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
            }
             else {
                try {
                    String sql1 = "INSERT INTO TaiKhoanNganHang (maNH, tenNH, tenTK, soTK, binNH) VALUES (?, ?, ?, ?, ?)";
                    PreparedStatement ps1 = conn.prepareStatement(sql1);
                    ps1.setString(1, jTextField15.getText());
                    ps1.setString(2, jComboBox2.getSelectedItem().toString());
                    ps1.setString(3, jTextField16.getText());
                    ps1.setString(4, jTextField17.getText());
                    ps1.setString(5, bankCodes.get(jComboBox2.getSelectedItem().toString()));          
                    ps1.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Thêm thành công");
                    inTableQLTKNH();
                    jTextField15.setText("");
                    jTextField16.setText("");
                    jTextField17.setText("");
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_themtknhMouseClicked

    private void suatknhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suatknhMouseClicked
        // TODO add your handling code here:
        Map<String, String> bankCodes = new HashMap<>();
            bankCodes.put("MB Bank", "970422");
            bankCodes.put("Agribank", "3");
            bankCodes.put("VietinBank", "2");
            bankCodes.put("SCB", "970401");
            bankCodes.put("DongA Bank", "970402");
            bankCodes.put("Techcombank", "970403");
            bankCodes.put("Vietcombank", "970404");
            bankCodes.put("ACB", "970406");
            bankCodes.put("VPBank", "970407");
            bankCodes.put("BIDV", "970408");
        try {
            conn = new connectDB().getConnection();
        } catch (Exception e) {
            e.printStackTrace();
        }
        if(jTextField15.getText().equals("")||jTextField16.getText().equals("")||jTextField17.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
            return;
        }
        else{
            try{
                String sql = "update TaiKhoanNganHang set tenNH = ?, tenTK = ?, soTK = ?, binNH = ? where maNH = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, jComboBox2.getSelectedItem().toString());
                ps.setString(2, jTextField16.getText());
                ps.setString(3, jTextField17.getText());
                ps.setString(4, bankCodes.get(jComboBox2.getSelectedItem().toString()));
                ps.setString(5, jTextField15.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Sửa thành công");
                inTableQLTKNH();
                jTextField16.setText("");
                jTextField17.setText("");
                jTextField15.setText("");

            } catch(Exception e){
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_suatknhMouseClicked

    private void xoatknhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoatknhMouseClicked
        // TODO add your handling code here:
        try {
            conn = new connectDB().getConnection();
        } catch (Exception e) {
            e.printStackTrace();
        }
        if(jTextField15.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn tài khoản cần xóa");
            return;
        }
        else{
            try{
                String sql = "delete from TaiKhoanNganHang where maNH = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, jTextField15.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                inTableQLTKNH();

            } catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_xoatknhMouseClicked

    private void themtknh1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_themtknh1MouseClicked
        // TODO add your handling code here:
        loginAdmin.setVisible(true);
        settingAdmin.setVisible(false);
    }//GEN-LAST:event_themtknh1MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
        //set các ô về trống
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        //set các ô về trống
        jTextField15.setText("");
        jTextField16.setText("");
        jTextField17.setText("");
    }//GEN-LAST:event_jPanel5MouseClicked

    private void inTableQLTKNH(){
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        try {
            conn = new connectDB().getConnection();
            String sql = "SELECT * FROM TaiKhoanNganHang";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString("maNH").trim());
                row.add(rs.getString("tenNH").trim());
                row.add(rs.getString("tenTK").trim());
                row.add(rs.getString("soTK").trim());
                row.add(rs.getString("binNH").trim());
                model.addRow(row);
            }
            jTable2.setModel(model);
        } catch (Exception e) {
        }
    }

    private void inTableQLTK(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        try {
            conn = new connectDB().getConnection();
            String sql = "SELECT * FROM NhanVien";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString("maNV").trim());
                row.add(rs.getString("ten").trim());
                row.add(rs.getString("taikhoan").trim());
                row.add(rs.getString("matkhau").trim());
                row.add(rs.getString("quyenhan").trim());
                model.addRow(row);
            }
            jTable1.setModel(model);
        } catch (Exception e) {
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dangnhap;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JPanel loginAdmin;
    private javax.swing.JTabbedPane settingAdmin;
    private javax.swing.JPanel suatk;
    private javax.swing.JPanel suatknh;
    private javax.swing.JPanel taotk;
    private javax.swing.JPanel themtknh;
    private javax.swing.JPanel themtknh1;
    private javax.swing.JPanel xoatk;
    private javax.swing.JPanel xoatknh;
    // End of variables declaration//GEN-END:variables
}
