/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.source.Form;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;

import com.source.Sql.connectDB;

/**
 *
 * @author HP
 */
public class themdichvu extends javax.swing.JPanel {

    connectDB cn = new connectDB();
    Connection conn;

    /**
     * Creates new form themdichvu
     */
    public themdichvu() {
        initComponents();
        inTableKH();
        showNhanVien();
        inTableHDDV();
        inTableCTHDDV();
        inTableDV();
        Thread thread = new Thread(() -> {
            timkhachhang.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
                public void changedUpdate(javax.swing.event.DocumentEvent e) {
                    TimKhachHang();
                }

                public void removeUpdate(javax.swing.event.DocumentEvent e) {
                    TimKhachHang();
                }

                public void insertUpdate(javax.swing.event.DocumentEvent e) {
                    TimKhachHang();
                }

            });
        });
        thread.start();
        Thread thread1 = new Thread(() -> {
            soluongg.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                thanhtien();
            }
        });
        });
        thread1.start();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        HDDV = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        timkhachhang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        makh = new javax.swing.JTextField();
        nguoilap = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        them = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        chitiet = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Xoa21 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        CTHDDV = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        giaa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        madv = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        thanhtienn = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        maCT = new javax.swing.JTextField();
        maHDd = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tongtien = new javax.swing.JTextField();
        luuHD = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        thoat = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        them2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        xoa2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        sua2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        soluongg = new javax.swing.JSpinner();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.CardLayout());

        HDDV.setBackground(new java.awt.Color(153, 153, 153));
        HDDV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã KH", "Tên", "Số điện thoại", "Địa chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        HDDV.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 192));

        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HDDV", "Mã KH", "Mã Nhân Viên", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setRowHeight(30);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        HDDV.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 346, 889, 180));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        timkhachhang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Nhập tên khách hàng muốn tìm");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(timkhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(timkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        HDDV.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 0, -1, -1));

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        makh.setEditable(false);
        makh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nguoilap.setEditable(false);
        nguoilap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField13.setEditable(false);
        jTextField13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã nhân viên");

        jLabel3.setText("Mã KH");

        jLabel4.setText("Mã tự động");

        them.setBackground(new java.awt.Color(102, 102, 102));
        them.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                themMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tạo");

        javax.swing.GroupLayout themLayout = new javax.swing.GroupLayout(them);
        them.setLayout(themLayout);
        themLayout.setHorizontalGroup(
            themLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(themLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        themLayout.setVerticalGroup(
            themLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(themLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chitiet.setBackground(new java.awt.Color(102, 102, 102));
        chitiet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chitiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chitietMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Chi tiết");

        javax.swing.GroupLayout chitietLayout = new javax.swing.GroupLayout(chitiet);
        chitiet.setLayout(chitietLayout);
        chitietLayout.setHorizontalGroup(
            chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chitietLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chitietLayout.setVerticalGroup(
            chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chitietLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Xoa21.setBackground(new java.awt.Color(102, 102, 102));
        Xoa21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Xoa21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Xoa21MouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Xóa");

        javax.swing.GroupLayout Xoa21Layout = new javax.swing.GroupLayout(Xoa21);
        Xoa21.setLayout(Xoa21Layout);
        Xoa21Layout.setHorizontalGroup(
            Xoa21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Xoa21Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel19)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        Xoa21Layout.setVerticalGroup(
            Xoa21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Xoa21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(makh, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nguoilap, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(145, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Xoa21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(chitiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nguoilap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chitiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Xoa21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        HDDV.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 198, 889, 150));

        jPanel2.add(HDDV, "card3");

        CTHDDV.setBackground(new java.awt.Color(153, 153, 153));
        CTHDDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CTHDDVMouseClicked(evt);
            }
        });

        jTable3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Đơn vị tính", "Giá dịch vụ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setRowHeight(30);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel5.setText("Mã DV");

        giaa.setEditable(false);
        giaa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Giá");

        madv.setEditable(false);
        madv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Số lượng");

        jLabel9.setText("Thành tiền");

        thanhtienn.setEditable(false);
        thanhtienn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã CT", "Mã HDDV", "Mã DV", "Giá DV", "Số lượng", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.setRowHeight(30);
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jLabel11.setText("Mã tự động");

        maCT.setEditable(false);
        maCT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        maHDd.setEditable(false);
        maHDd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setText("Mã HĐ");

        jLabel13.setText("Tổng tiền");

        tongtien.setEditable(false);
        tongtien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        luuHD.setBackground(new java.awt.Color(102, 102, 102));
        luuHD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        luuHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                luuHDMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Lưu HD");

        javax.swing.GroupLayout luuHDLayout = new javax.swing.GroupLayout(luuHD);
        luuHD.setLayout(luuHDLayout);
        luuHDLayout.setHorizontalGroup(
            luuHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(luuHDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        luuHDLayout.setVerticalGroup(
            luuHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(luuHDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        thoat.setBackground(new java.awt.Color(102, 102, 102));
        thoat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thoatMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Thoát");

        javax.swing.GroupLayout thoatLayout = new javax.swing.GroupLayout(thoat);
        thoat.setLayout(thoatLayout);
        thoatLayout.setHorizontalGroup(
            thoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thoatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        thoatLayout.setVerticalGroup(
            thoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thoatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        them2.setBackground(new java.awt.Color(102, 102, 102));
        them2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        them2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                them2MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Thêm");

        javax.swing.GroupLayout them2Layout = new javax.swing.GroupLayout(them2);
        them2.setLayout(them2Layout);
        them2Layout.setHorizontalGroup(
            them2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(them2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        them2Layout.setVerticalGroup(
            them2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(them2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        xoa2.setBackground(new java.awt.Color(102, 102, 102));
        xoa2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xoa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xoa2MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Xóa");

        javax.swing.GroupLayout xoa2Layout = new javax.swing.GroupLayout(xoa2);
        xoa2.setLayout(xoa2Layout);
        xoa2Layout.setHorizontalGroup(
            xoa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xoa2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(16, 16, 16))
        );
        xoa2Layout.setVerticalGroup(
            xoa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xoa2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sua2.setBackground(new java.awt.Color(102, 102, 102));
        sua2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sua2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sua2MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Sửa");

        javax.swing.GroupLayout sua2Layout = new javax.swing.GroupLayout(sua2);
        sua2.setLayout(sua2Layout);
        sua2Layout.setHorizontalGroup(
            sua2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sua2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sua2Layout.setVerticalGroup(
            sua2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sua2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CTHDDVLayout = new javax.swing.GroupLayout(CTHDDV);
        CTHDDV.setLayout(CTHDDVLayout);
        CTHDDVLayout.setHorizontalGroup(
            CTHDDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CTHDDVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CTHDDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(30, 30, 30)
                .addGroup(CTHDDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CTHDDVLayout.createSequentialGroup()
                        .addComponent(them2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(sua2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CTHDDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(CTHDDVLayout.createSequentialGroup()
                            .addComponent(luuHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(thoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CTHDDVLayout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CTHDDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CTHDDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CTHDDVLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(104, 104, 104))
                                .addComponent(jLabel5)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CTHDDVLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(143, 143, 143)))
                            .addGroup(CTHDDVLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maCT, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CTHDDVLayout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maHDd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(xoa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CTHDDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(thanhtienn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(CTHDDVLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(soluongg, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(giaa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(madv, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
        );
        CTHDDVLayout.setVerticalGroup(
            CTHDDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CTHDDVLayout.createSequentialGroup()
                .addGroup(CTHDDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CTHDDVLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(CTHDDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(madv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CTHDDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(giaa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CTHDDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soluongg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CTHDDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(thanhtienn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CTHDDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(them2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sua2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CTHDDVLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(CTHDDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CTHDDVLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CTHDDVLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(xoa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CTHDDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(maCT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CTHDDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(maHDd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CTHDDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(CTHDDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(thoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(luuHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jPanel2.add(CTHDDV, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chitietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chitietMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int i = jTable2.getSelectedRow();
        if (i >= 0) {
            maHDd.setText(model.getValueAt(i, 0).toString());
            HDDV.setVisible(false);
            CTHDDV.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "Chọn hóa đơn cần xem chi tiết");
        }
        
    }//GEN-LAST:event_chitietMouseClicked

    private void thoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thoatMouseClicked
        // TODO add your handling code here:
        HDDV.setVisible(true);
        CTHDDV.setVisible(false);

    }//GEN-LAST:event_thoatMouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
                int i = jTable3.getSelectedRow();
                if(i>=0){
                    madv.setText(model.getValueAt(i, 0).toString());
                    giaa.setText(model.getValueAt(i, 3).toString());
                }
    }//GEN-LAST:event_jTable3MouseClicked

    private void them2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_them2MouseClicked
        // TODO add your handling code here:
        try {
            conn = new connectDB().getConnection();
            String sql = "{call InsertChiTietHoaDonDichVu(?, ?, ?, ?, ?)}";
            CallableStatement cs = conn.prepareCall(sql);
            cs.setString(1, maHDd.getText());
            cs.setString(2, madv.getText());
            cs.setFloat(3, Float.parseFloat(giaa.getText()));
            cs.setInt(4, Integer.parseInt(soluongg.getValue().toString()));
            cs.setFloat(5, Float.parseFloat(giaa.getText()) * Integer.parseInt(soluongg.getValue().toString()));
            cs.executeUpdate();
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            inTableCTHDDV();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Thêm thất bại: " + e.getMessage());
        }
    }//GEN-LAST:event_them2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int i = jTable1.getSelectedRow();
        if (i >= 0) {
            makh.setText(model.getValueAt(i, 0).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void themMouseClicked(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
        try {
            conn = new connectDB().getConnection();
            String sql = "{call InsertHoaDonDichVu(?, ?, ?)}";
            CallableStatement cs = conn.prepareCall(sql);
            cs.setString(1, makh.getText());
            cs.setString(2, nguoilap.getText());
            cs.setFloat(3, 0);
            cs.executeUpdate();
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            inTableHDDV();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Thêm thất bại: " + e.getMessage());
        }
        }

    private void xoa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoa2MouseClicked
        // TODO add your handling code here:
        try {
            conn = new connectDB().getConnection();
            String sql = "DELETE FROM ChiTietHoaDonDichVu WHERE maCTHDDV = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, maCT.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            inTableCTHDDV();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
    }//GEN-LAST:event_xoa2MouseClicked

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        int i = jTable4.getSelectedRow();
        if (i >= 0) {
            maCT.setText(model.getValueAt(i, 0).toString());
            maHDd.setText(model.getValueAt(i, 1).toString());
            madv.setText(model.getValueAt(i, 2).toString());
            giaa.setText(model.getValueAt(i, 3).toString());
            soluongg.setValue(Integer.parseInt(model.getValueAt(i, 4).toString()));
            
            // thanhtienn.setText(model.getValueAt(i, 5).toString());
        }
    }//GEN-LAST:event_jTable4MouseClicked

    private void sua2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sua2MouseClicked
        // TODO add your handling code here:
        try {
            conn = new connectDB().getConnection();
            String sql = "UPDATE ChiTietHoaDonDichVu SET maHDDV = ?, maDV = ?, giaDV = ?, soluong = ?, thanhtien = ? WHERE maCTHDDV = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, maHDd.getText());
            ps.setString(2, madv.getText());
            ps.setString(3, giaa.getText());
            ps.setString(4, soluongg.getValue().toString());
            ps.setString(5, thanhtienn.getText());
            ps.setString(6, maCT.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            inTableCTHDDV();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
    }//GEN-LAST:event_sua2MouseClicked

    private void luuHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_luuHDMouseClicked
        // TODO add your handling code here:
        try {
            conn = new connectDB().getConnection();
            String sql = "SELECT SUM(thanhtien) AS sum_thanhtien FROM ChiTietHoaDonDichVu WHERE maHDDV = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, maHDd.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {  
                //nếu là NULL thì trả về 0
                tongtien.setText(String.valueOf(rs.getFloat("sum_thanhtien")));
                
            }
            String sql2 = "UPDATE HoaDonDichVu SET tongTienDV = ? WHERE maHDDV = ?";
            PreparedStatement ps2 = conn.prepareStatement(sql2);
            ps2.setString(1, tongtien.getText());
            ps2.setString(2, maHDd.getText());
            ps2.executeUpdate();
            JOptionPane.showMessageDialog(this, "Lưu thành công");
            inTableHDDV();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lưu thất bại" + e.getMessage());
        }
    }//GEN-LAST:event_luuHDMouseClicked

    private void CTHDDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CTHDDVMouseClicked
        // TODO add your handling code here:
        inTableCTHDDV();
        inTableDV();
        //set về trống các ô nhập
        maCT.setText("");
        madv.setText("");
        giaa.setText("");
        soluongg.setValue(0);

    }//GEN-LAST:event_CTHDDVMouseClicked

    private void Xoa21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Xoa21MouseClicked
        // TODO add your handling code here:
        try {
            conn = new connectDB().getConnection();
            String sql = "DELETE FROM HoaDonDichVu WHERE maHDDV = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, jTextField13.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            inTableHDDV();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Xóa thất bại, vui lòng xóa dữ liệu chi tiết trước!");
        }
    }//GEN-LAST:event_Xoa21MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int i = jTable2.getSelectedRow();
        if (i >= 0) {
            jTextField13.setText(model.getValueAt(i, 0).toString());
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        inTableKH();
    }//GEN-LAST:event_jPanel5MouseClicked

    private void inTableKH() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        try {
            conn = new connectDB().getConnection();
            String sql = "SELECT * FROM KhachHang";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString("maKH").trim());
                row.add(rs.getString("hoten").trim());
                row.add(rs.getString("sdt").trim());
                row.add(rs.getString("diachi").trim());
                model.addRow(row);
            }
            jTable1.setModel(model);
        } catch (Exception e) {
        }
    }

    private void TimKhachHang() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        try {
            conn = new connectDB().getConnection();
            //có thể tìm nội dung ở tất cả các cột trong database
            String sql = "SELECT * FROM KhachHang WHERE maKH LIKE ? OR hoten LIKE ? OR sdt LIKE ? OR diachi LIKE ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, "%" + timkhachhang.getText() + "%");
            ps.setString(2, "%" + timkhachhang.getText() + "%");
            ps.setString(3, "%" + timkhachhang.getText() + "%");
            ps.setString(4, "%" + timkhachhang.getText() + "%");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString("maKH").trim());
                row.add(rs.getString("hoten").trim());
                row.add(rs.getString("sdt").trim());
                row.add(rs.getString("diachi").trim());
                model.addRow(row);
                jTable1.setModel(model);
            }
        } catch (Exception e) {
        }
    }

    private void inTableDV(){
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.setRowCount(0);
        try {
            conn = new connectDB().getConnection();
            String sql = "SELECT * FROM DichVu";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString("maDV").trim());
                row.add(rs.getString("tenDV").trim());
                row.add(rs.getString("donvitinh").trim());
                row.add(rs.getString("giaDV").trim());
                model.addRow(row);
            }
            jTable3.setModel(model);
        } catch (Exception e) {
        }
    }
    private void thanhtien(){
        float gia = Float.parseFloat(giaa.getText());
        float soluong = Float.parseFloat(soluongg.getValue().toString());
        float thanhtien = gia * soluong;
        thanhtienn.setText(String.valueOf(thanhtien));
    }
    private void inTableCTHDDV(){
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        model.setRowCount(0);
        try {
            conn = new connectDB().getConnection();
            String sql = "SELECT * FROM ChiTietHoaDonDichVu WHERE maHDDV = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, maHDd.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString("maCTHDDV").trim());
                row.add(rs.getString("maHDDV").trim());
                row.add(rs.getString("maDV").trim());
                row.add(Float.parseFloat(rs.getString("giaDV").trim()));
                row.add(Integer.parseInt(rs.getString("soluong").trim()));
                row.add(Float.parseFloat(rs.getString("thanhtien").trim()));
                model.addRow(row);
            }
            jTable4.setModel(model);
        } catch (Exception e) {
        }
    }
    private void showNhanVien(){
        //ghi ra ten nhân viên có trinhtrang = 1
        try {
            conn = new connectDB().getConnection();
            String sql = "SELECT * FROM NhanVien WHERE trangthai = 1";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                nguoilap.setText(rs.getString("maNV").trim());
            }
        } catch (Exception e) {
        }
    }
    private void inTableHDDV(){
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        try {
            conn = new connectDB().getConnection();
            String sql = "SELECT * FROM HoaDonDichVu";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString("maHDDV").trim());
                row.add(rs.getString("maKH").trim());
                row.add(rs.getString("maNV").trim());
                row.add(rs.getString("tongTienDV").trim());
                model.addRow(row);
            }
            jTable2.setModel(model);
        } catch (Exception e) {
        }
    }
    // private void tongTienDV(){
    //     try {
    //         conn = new connectDB().getConnection();
    //         String sql = "SELECT SUM(thanhtien) FROM ChiTietHoaDonDichVu WHERE maHDDV = ?";
    //         PreparedStatement ps = conn.prepareStatement(sql);
    //         ps.setString(1, maHDd.getText());
    //         ResultSet rs = ps.executeQuery();
    //         while (rs.next()) {
    //             tongtien.setText(rs.getString("SUM(thanhtien)").trim());
    //         }
    //     } catch (Exception e) {
    //     }
    // }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CTHDDV;
    private javax.swing.JPanel HDDV;
    private javax.swing.JPanel Xoa21;
    private javax.swing.JPanel chitiet;
    private javax.swing.JTextField giaa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JPanel luuHD;
    private javax.swing.JTextField maCT;
    private javax.swing.JTextField maHDd;
    private javax.swing.JTextField madv;
    private javax.swing.JTextField makh;
    private javax.swing.JTextField nguoilap;
    private javax.swing.JSpinner soluongg;
    private javax.swing.JPanel sua2;
    private javax.swing.JTextField thanhtienn;
    private javax.swing.JPanel them;
    private javax.swing.JPanel them2;
    private javax.swing.JPanel thoat;
    private javax.swing.JTextField timkhachhang;
    private javax.swing.JTextField tongtien;
    private javax.swing.JPanel xoa2;
    // End of variables declaration//GEN-END:variables
}
