/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.source.Main;

import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

import com.source.LoginForm.LoginForm;
import javax.swing.WindowConstants;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import com.source.Sql.connectDB;

/**
 *
 * @author HP
 */
public class Main extends javax.swing.JFrame {
    connectDB connect = new connectDB();
    Connection conn;


    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            
            @Override
            public void windowClosing(WindowEvent e) {
                
                int confirm = JOptionPane.showOptionDialog(
                        null, "Bạn có chắc muốn thoát?", 
                        "Thông báo!", JOptionPane.YES_NO_OPTION, 
                        JOptionPane.QUESTION_MESSAGE, null, null, null);
                if (confirm == JOptionPane.YES_OPTION) {
                    //set trangthai trong bảng NhanVien nơi nhân viên có tranthai dang nhập là 1 thành 0
                    try {
                        conn = new connectDB().getConnection();
                        String sql = "UPDATE NhanVien SET trangthai = 0 WHERE trangthai = 1";
                        PreparedStatement ps = conn.prepareStatement(sql);
                        ps.executeUpdate();
                        conn.close();
                    } catch (Exception ex) {
                        System.out.println(ex);
                    }
                    System.exit(0);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        trangchu1 = new com.source.Form.trangchu();
        themdichvu1 = new com.source.Form.themdichvu();
        thuephong1 = new com.source.Form.thuephong();
        qlphong1 = new com.source.Form.qlphong();
        qldichvu1 = new com.source.Form.qldichvu();
        qlkhachhang1 = new com.source.Form.qlkhachhang();
        traphong1 = new com.source.Form.traphong();
        qlhoadon1 = new com.source.Form.qlhoadon();
        doimatkhau1 = new com.source.Form.doimatkhau();
        taohoadonthanhtoan1 = new com.source.Form.taohoadonthanhtoan();
        jPanel2 = new javax.swing.JPanel();
        daytime1 = new com.source.Component.daytime();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        infouser2 = new com.source.Component.infouser();
        jPanel4 = new javax.swing.JPanel();
        qlhoadon = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        qlphong = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        qlkhachhang = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        doimk = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        dangxuat = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        qldichvu = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        thuephong = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        traphong = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        themdichvu = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        trangchu = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        taohoadontinhtien = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Manager");
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.CardLayout());
        jPanel1.add(trangchu1, "card10");
        jPanel1.add(themdichvu1, "card6");
        jPanel1.add(thuephong1, "card7");
        jPanel1.add(qlphong1, "card3");
        jPanel1.add(qldichvu1, "card5");
        jPanel1.add(qlkhachhang1, "card4");
        jPanel1.add(traphong1, "card8");
        jPanel1.add(qlhoadon1, "card9");
        jPanel1.add(doimatkhau1, "card10");
        jPanel1.add(taohoadonthanhtoan1, "card11");

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 76, 1024, 619));

        jPanel2.setBackground(new java.awt.Color(0, 124, 124));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        daytime1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(daytime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 142, 142));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setBackground(new java.awt.Color(0, 84, 42));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\code\\java\\DACS1Java\\QLKS\\QLKSjava\\src\\com\\source\\Icon\\opened-door-aperture-logoo.png")); // NOI18N
        jLabel1.setText("HOTEL MANAGER");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, -1, -1));

        infouser2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(infouser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        jPanel4.setBackground(new java.awt.Color(0, 124, 124));

        qlhoadon.setBackground(new java.awt.Color(173, 181, 183));
        qlhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qlhoadonMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Quản lý - Thống kê hóa đơn");

        javax.swing.GroupLayout qlhoadonLayout = new javax.swing.GroupLayout(qlhoadon);
        qlhoadon.setLayout(qlhoadonLayout);
        qlhoadonLayout.setHorizontalGroup(
            qlhoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qlhoadonLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        qlhoadonLayout.setVerticalGroup(
            qlhoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qlhoadonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        qlphong.setBackground(new java.awt.Color(173, 181, 183));
        qlphong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qlphongMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Quản lý phòng");

        javax.swing.GroupLayout qlphongLayout = new javax.swing.GroupLayout(qlphong);
        qlphong.setLayout(qlphongLayout);
        qlphongLayout.setHorizontalGroup(
            qlphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qlphongLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        qlphongLayout.setVerticalGroup(
            qlphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qlphongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        qlkhachhang.setBackground(new java.awt.Color(173, 181, 183));
        qlkhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qlkhachhangMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Quản lý khách hàng");

        javax.swing.GroupLayout qlkhachhangLayout = new javax.swing.GroupLayout(qlkhachhang);
        qlkhachhang.setLayout(qlkhachhangLayout);
        qlkhachhangLayout.setHorizontalGroup(
            qlkhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qlkhachhangLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        qlkhachhangLayout.setVerticalGroup(
            qlkhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qlkhachhangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Quản lý");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Hệ thống");

        doimk.setBackground(new java.awt.Color(173, 181, 183));
        doimk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doimkMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Cài đặt");

        javax.swing.GroupLayout doimkLayout = new javax.swing.GroupLayout(doimk);
        doimk.setLayout(doimkLayout);
        doimkLayout.setHorizontalGroup(
            doimkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doimkLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        doimkLayout.setVerticalGroup(
            doimkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doimkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dangxuat.setBackground(new java.awt.Color(173, 181, 183));
        dangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dangxuatMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Đăng xuất");

        javax.swing.GroupLayout dangxuatLayout = new javax.swing.GroupLayout(dangxuat);
        dangxuat.setLayout(dangxuatLayout);
        dangxuatLayout.setHorizontalGroup(
            dangxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dangxuatLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dangxuatLayout.setVerticalGroup(
            dangxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dangxuatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        qldichvu.setBackground(new java.awt.Color(173, 181, 183));
        qldichvu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qldichvuMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Quản lý dịch vụ");

        javax.swing.GroupLayout qldichvuLayout = new javax.swing.GroupLayout(qldichvu);
        qldichvu.setLayout(qldichvuLayout);
        qldichvuLayout.setHorizontalGroup(
            qldichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qldichvuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        qldichvuLayout.setVerticalGroup(
            qldichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qldichvuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        thuephong.setBackground(new java.awt.Color(173, 181, 183));
        thuephong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thuephongMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Thuê phòng");

        javax.swing.GroupLayout thuephongLayout = new javax.swing.GroupLayout(thuephong);
        thuephong.setLayout(thuephongLayout);
        thuephongLayout.setHorizontalGroup(
            thuephongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thuephongLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        thuephongLayout.setVerticalGroup(
            thuephongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thuephongLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Chức năng");

        traphong.setBackground(new java.awt.Color(173, 181, 183));
        traphong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                traphongMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Trả phòng");

        javax.swing.GroupLayout traphongLayout = new javax.swing.GroupLayout(traphong);
        traphong.setLayout(traphongLayout);
        traphongLayout.setHorizontalGroup(
            traphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(traphongLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        traphongLayout.setVerticalGroup(
            traphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(traphongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        themdichvu.setBackground(new java.awt.Color(173, 181, 183));
        themdichvu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                themdichvuMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Thêm dịch vụ");

        javax.swing.GroupLayout themdichvuLayout = new javax.swing.GroupLayout(themdichvu);
        themdichvu.setLayout(themdichvuLayout);
        themdichvuLayout.setHorizontalGroup(
            themdichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(themdichvuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        themdichvuLayout.setVerticalGroup(
            themdichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, themdichvuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        trangchu.setBackground(new java.awt.Color(173, 181, 183));
        trangchu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trangchuMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setText("Trang chủ");

        javax.swing.GroupLayout trangchuLayout = new javax.swing.GroupLayout(trangchu);
        trangchu.setLayout(trangchuLayout);
        trangchuLayout.setHorizontalGroup(
            trangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trangchuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        trangchuLayout.setVerticalGroup(
            trangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trangchuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        taohoadontinhtien.setBackground(new java.awt.Color(173, 181, 183));
        taohoadontinhtien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taohoadontinhtienMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Tạo hóa đơn - Tính tiền");

        javax.swing.GroupLayout taohoadontinhtienLayout = new javax.swing.GroupLayout(taohoadontinhtien);
        taohoadontinhtien.setLayout(taohoadontinhtienLayout);
        taohoadontinhtienLayout.setHorizontalGroup(
            taohoadontinhtienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taohoadontinhtienLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        taohoadontinhtienLayout.setVerticalGroup(
            taohoadontinhtienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taohoadontinhtienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 170, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 122, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(themdichvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(traphong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(thuephong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doimk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dangxuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(trangchu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(taohoadontinhtien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(qlhoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(qldichvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(qlkhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(qlphong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(trangchu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thuephong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(traphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(themdichvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taohoadontinhtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qlphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qlkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qldichvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qlhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doimk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, -1, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trangchuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trangchuMouseClicked
        // TODO add your handling code here:
        handleButtonMouseClicked(trangchu, new javax.swing.JPanel[]{trangchu, thuephong, traphong, themdichvu, taohoadontinhtien, qlphong, qlkhachhang, qldichvu, qlhoadon, doimk, dangxuat});
        trangchu1.setVisible(true);
        thuephong1.setVisible(false);
        traphong1.setVisible(false);
        themdichvu1.setVisible(false);
        qlphong1.setVisible(false);
        qlkhachhang1.setVisible(false);
        qldichvu1.setVisible(false);
        qlhoadon1.setVisible(false);
        doimatkhau1.setVisible(false);
        taohoadonthanhtoan1.setVisible(false);
    }//GEN-LAST:event_trangchuMouseClicked

    private void taohoadontinhtienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taohoadontinhtienMouseClicked
        // TODO add your handling code here:
        handleButtonMouseClicked(taohoadontinhtien, new javax.swing.JPanel[]{trangchu, thuephong, traphong, themdichvu, taohoadontinhtien, qlphong, qlkhachhang, qldichvu, qlhoadon, doimk, dangxuat});
        taohoadonthanhtoan1.setVisible(true);
        trangchu1.setVisible(false);
        thuephong1.setVisible(false);
        traphong1.setVisible(false);
        themdichvu1.setVisible(false);
        qlphong1.setVisible(false);
        qlkhachhang1.setVisible(false);
        qldichvu1.setVisible(false);
        qlhoadon1.setVisible(false);
        doimatkhau1.setVisible(false);
        
    }//GEN-LAST:event_taohoadontinhtienMouseClicked

    private void changeButtonBackground(javax.swing.JPanel button) {
        button.setBackground(new java.awt.Color(121, 140, 146));
    }

    private void changeButtonBackground2(javax.swing.JPanel button) {
        button.setBackground(new java.awt.Color(173, 181, 183));
    }

    private void handleButtonMouseClicked(javax.swing.JPanel button, javax.swing.JPanel[] buttons) {
        changeButtonBackground(button);
        for (javax.swing.JPanel btn : buttons) {
            if (btn != button) {
                changeButtonBackground2(btn);
            }
        }
    }

    private void thuephongMouseClicked(java.awt.event.MouseEvent evt) {                                       
        handleButtonMouseClicked(thuephong, new javax.swing.JPanel[]{trangchu, thuephong, traphong, themdichvu, taohoadontinhtien, qlphong, qlkhachhang, qldichvu, qlhoadon, doimk, dangxuat});
        thuephong1.setVisible(true);
        traphong1.setVisible(false);
        themdichvu1.setVisible(false);
        qlphong1.setVisible(false);
        qlkhachhang1.setVisible(false);
        qldichvu1.setVisible(false);
        qlhoadon1.setVisible(false);
        doimatkhau1.setVisible(false);
        trangchu1.setVisible(false);
        taohoadonthanhtoan1.setVisible(false);
        
    }

    private void traphongMouseClicked(java.awt.event.MouseEvent evt) {  
        handleButtonMouseClicked(traphong, new javax.swing.JPanel[]{trangchu, thuephong, traphong, themdichvu, taohoadontinhtien, qlphong, qlkhachhang, qldichvu, qlhoadon, doimk, dangxuat});
        traphong1.setVisible(true);
        thuephong1.setVisible(false);
        themdichvu1.setVisible(false);
        qlphong1.setVisible(false);
        qlkhachhang1.setVisible(false);
        qldichvu1.setVisible(false);
        qlhoadon1.setVisible(false);
        doimatkhau1.setVisible(false);
        trangchu1.setVisible(false);    
        taohoadonthanhtoan1.setVisible(false);
        
    }

    private void themdichvuMouseClicked(java.awt.event.MouseEvent evt) {                                        
        handleButtonMouseClicked(themdichvu, new javax.swing.JPanel[]{trangchu, thuephong, traphong, themdichvu, taohoadontinhtien, qlphong, qlkhachhang, qldichvu, qlhoadon, doimk, dangxuat});
        themdichvu1.setVisible(true);
        traphong1.setVisible(false);
        thuephong1.setVisible(false);
        qlphong1.setVisible(false);
        qlkhachhang1.setVisible(false);
        qldichvu1.setVisible(false);
        qlhoadon1.setVisible(false);
        doimatkhau1.setVisible(false);
        trangchu1.setVisible(false);
        taohoadonthanhtoan1.setVisible(false);
    }

    private void qlphongMouseClicked(java.awt.event.MouseEvent evt) {                                     
        handleButtonMouseClicked(qlphong, new javax.swing.JPanel[]{trangchu, thuephong, traphong, themdichvu, taohoadontinhtien, qlphong, qlkhachhang, qldichvu, qlhoadon, doimk, dangxuat});
        qlphong1.setVisible(true);
        qlkhachhang1.setVisible(false);
        qldichvu1.setVisible(false);
        qlhoadon1.setVisible(false);
        doimatkhau1.setVisible(false);
        themdichvu1.setVisible(false);
        traphong1.setVisible(false);
        thuephong1.setVisible(false);
        trangchu1.setVisible(false);
        taohoadonthanhtoan1.setVisible(false);
    }

    private void qlkhachhangMouseClicked(java.awt.event.MouseEvent evt) {                                         
        handleButtonMouseClicked(qlkhachhang, new javax.swing.JPanel[]{trangchu, thuephong, traphong, themdichvu, taohoadontinhtien, qlphong, qlkhachhang, qldichvu, qlhoadon, doimk, dangxuat});
        qlkhachhang1.setVisible(true);
        qldichvu1.setVisible(false);
        qlhoadon1.setVisible(false);
        doimatkhau1.setVisible(false);
        thuephong1.setVisible(false);
        traphong1.setVisible(false);
        themdichvu1.setVisible(false);
        qlphong1.setVisible(false);
        trangchu1.setVisible(false);
        taohoadonthanhtoan1.setVisible(false);

    }

    private void qldichvuMouseClicked(java.awt.event.MouseEvent evt) {                                      
        handleButtonMouseClicked(qldichvu, new javax.swing.JPanel[]{trangchu, thuephong, traphong, themdichvu, taohoadontinhtien, qlphong, qlkhachhang, qldichvu, qlhoadon, doimk, dangxuat});
        qldichvu1.setVisible(true);
        qlhoadon1.setVisible(false);
        doimatkhau1.setVisible(false);
        thuephong1.setVisible(false);
        traphong1.setVisible(false);
        themdichvu1.setVisible(false);
        qlphong1.setVisible(false);
        qlkhachhang1.setVisible(false);
        trangchu1.setVisible(false);
        taohoadonthanhtoan1.setVisible(false);

    }

    private void qlhoadonMouseClicked(java.awt.event.MouseEvent evt) {                                      
        handleButtonMouseClicked(qlhoadon, new javax.swing.JPanel[]{trangchu, thuephong, traphong, themdichvu, taohoadontinhtien, qlphong, qlkhachhang, qldichvu, qlhoadon, doimk, dangxuat});
        qlhoadon1.setVisible(true);
        doimatkhau1.setVisible(false);
        thuephong1.setVisible(false);
        traphong1.setVisible(false);
        themdichvu1.setVisible(false);
        qlphong1.setVisible(false);
        qlkhachhang1.setVisible(false);
        qldichvu1.setVisible(false);
        trangchu1.setVisible(false);
        taohoadonthanhtoan1.setVisible(false);
    }

    private void doimkMouseClicked(java.awt.event.MouseEvent evt) {                                   
        handleButtonMouseClicked(doimk, new javax.swing.JPanel[]{trangchu, thuephong, traphong, themdichvu, taohoadontinhtien, qlphong, qlkhachhang, qldichvu, qlhoadon, doimk, dangxuat});
        doimatkhau1.setVisible(true);
        qlhoadon1.setVisible(false);
        thuephong1.setVisible(false);
        traphong1.setVisible(false);
        themdichvu1.setVisible(false);
        qlphong1.setVisible(false);
        qlkhachhang1.setVisible(false);
        qldichvu1.setVisible(false);
        trangchu1.setVisible(false);
        taohoadonthanhtoan1.setVisible(false);
        
    }

    private void dangxuatMouseClicked(java.awt.event.MouseEvent evt) {                                      
        handleButtonMouseClicked(dangxuat, new javax.swing.JPanel[]{trangchu, thuephong, traphong, themdichvu, taohoadontinhtien, qlphong, qlkhachhang, qldichvu, qlhoadon, doimk, dangxuat});
        LoginForm lg = new LoginForm();
        lg.setVisible(true);
        lg.setLocationRelativeTo(null);
        this.dispose();
                    try {
                        conn = new connectDB().getConnection();
                        String sql = "UPDATE NhanVien SET trangthai = 0 WHERE trangthai = 1";
                        PreparedStatement ps = conn.prepareStatement(sql);
                        ps.executeUpdate();
                        conn.close();
                    } catch (Exception ex) {
                        System.out.println(ex);
                    }
    }


    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main main = new Main();
                main.setLocationRelativeTo(null);
                main.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dangxuat;
    private com.source.Component.daytime daytime1;
    private com.source.Form.doimatkhau doimatkhau1;
    private javax.swing.JPanel doimk;
    private com.source.Component.infouser infouser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel qldichvu;
    private com.source.Form.qldichvu qldichvu1;
    private javax.swing.JPanel qlhoadon;
    private com.source.Form.qlhoadon qlhoadon1;
    private javax.swing.JPanel qlkhachhang;
    private com.source.Form.qlkhachhang qlkhachhang1;
    private javax.swing.JPanel qlphong;
    private com.source.Form.qlphong qlphong1;
    private com.source.Form.taohoadonthanhtoan taohoadonthanhtoan1;
    private javax.swing.JPanel taohoadontinhtien;
    private javax.swing.JPanel themdichvu;
    private com.source.Form.themdichvu themdichvu1;
    private javax.swing.JPanel thuephong;
    private com.source.Form.thuephong thuephong1;
    private javax.swing.JPanel trangchu;
    private com.source.Form.trangchu trangchu1;
    private javax.swing.JPanel traphong;
    private com.source.Form.traphong traphong1;
    // End of variables declaration//GEN-END:variables
}
